services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3000:3000" 
    environment:
      NODE_ENV: ${NODE_ENV} 
      LLM_BASE_URL: ${LLM_BASE_URL}
      LLM_API_KEY: ${LLM_API_KEY}
      LLM_MODEL: ${LLM_MODEL}
      SQLITE_DATABASE_URL: ${SQLITE_DATABASE_URL}

